# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 950f193b51334674655cb67dae17f9ca50cebebd28e97e7ca17bca5c660912c42e0533a3caff3a62c624bda4d3e57a0c90c782ab7b3016b308753ab1f3881edb

test:
  secret_key_base: 49646c88febf6e829dd9eeaabc4492870f303f67a748b1a5afd4badb6c207fc2a2642208d6e797c11f6f7f6ce7b68bed90a128e070b7240719c76483d8843444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
